apiVersion: v1
kind: Pod
metadata:
  generateName: blockchain-
  labels:
    app: sb-chain
spec:
  containers:
  - name: sb-chain
    image: gurbirbasi/sb-chain
    ports:
    - name: node-port
      containerPort: 5000
